### ISSUE TITLE
cryptocurrency rate

### ISSUE THREAD

**Issue by alkawman** [GeekMagicClock/HelloCubic-Lite#10]
How can I display information about BTC, LTC, etc? I just bought this thing today and didn't know there were different versions.

**Comment by eth030** [comment]
Same i am really disapointed, i bought this same device and it only shows weather and gif

**Comment by urtho** [comment]
IMHO this software is based on an open source GPL licence - so we can just request the source code and they cannot refuse. 
https://github.com/peng-zhihui/HoloCubic/blob/main/LICENSE

**Comment by GeekMagicClock** [comment]
Hello, buy before you read the specs, make sure no misleading.

**Comment by eth030** [comment]
> IMHO this software is based on an open source GPL licence - so we can just request the source code and they cannot refuse. 
> 
> https://github.com/peng-zhihui/HoloCubic/blob/main/LICENSE

How can we proceed with that, I would love to add an crypto scene for the halo lite.
