### ISSUE TITLE
Got my cube display “bricked”...

### ISSUE THREAD

**Issue by k0nradk** [GeekMagicClock/HelloCubic-Lite#22]
Is there some way to “revive” my cube that got bricked by uploading faulty firmware?

**Comment by GeekMagicClock** [comment]
Hi, what kind of faulty firmware?

**Comment by k0nradk** [comment]
It's just the original firmware that I tinkered with. It's my bad, I know. I wondered if there's perhaps a way to, like, access the memory directly and place the firmware file into it or something.

**Comment by k0nradk** [comment]
bump

**Comment by GeekMagicClock** [comment]
Sorry, I have to admit that this is beyond the scope of after-sales support. 

Caution: Before modifying device firmware, be prepared for irreversible consequences.

**Comment by k0nradk** [comment]
ok, thanks
