### ISSUE TITLE
Switching languages and region

### ISSUE THREAD

**Issue by Tony1881ynoT** [GeekMagicClock/HelloCubic-Lite#25]
Hi Team,

I've got my cubic from China and the interface is all in Chinese without the ability to select international cities...

Is there a way to update the firmware to have it switch to the "International" version please?

Thanks

**Comment by GeekMagicClock** [comment]
Hello, what it is displayed?

**Comment by Tony1881ynoT** [comment]
It’s all in Chinese so when I put in Auckland as the city and then I refresh the page, it just reverts back into the original default.
Current version is as below, it won’t update to the English version.




Thank You and Kind Regards,TonyW 

於 星期三, 12月 11, 2024, 00:14，GeekMagic ***@***.***> 寫道：




Hello, what it is displayed?

**Comment by GeekMagicClock** [comment]
@Tony1881ynoT  Hello, that is different model, https://github.com/GeekMagicClock/HelloCubic-V2 here's the english version, but I don't know if this can be updated to chinese version, since we do not sell chinese version directly, you may need to ask the retailer.
