### ISSUE TITLE
Opening up the source code

### ISSUE THREAD

**Issue by paaland** [GeekMagicClock/HelloCubic-Lite#27]
Can you please consider opening up the source code so you can receive help adding functionality and fixing bugs?
That would also close any issues regarding this device doing strange requets to chinese addresses which is why I have it isolated on a separat vlan with no access to my other devices. I simpy don't trust it.

If I knew this device was closed source I'd probably not have bought it.

**Comment by GeekMagicClock** [comment]
Hi, we never claimed open source anywhere anytime, it's on your own, if you don't trust it, I would say nothing, all on your own.

But we claimed here to others, we didn't send any "personal info" to China or any other country, all http/tcp data  can be captured, no our own server inside until now, but possible for future products for better product experience, like update firmware on device.

**Comment by paaland** [comment]
I just think this thing could be so much better if you got help from other developers via pull requests.

**Comment by alexis-ladurelle** [comment]
is there any way to make my own dashboard ?

**Comment by urtho** [comment]
IMHO this software is based on an open source GPL licence - so we can just request the source code and they cannot refuse. https://github.com/peng-zhihui/HoloCubic/blob/main/LICENSE

**Comment by IVANrn4hag** [comment]
Сделайте пожалуйста еще возможность запрашивать какие либо API что бы можно было засунуть туда что то свое, пробки или курс акций и т.д. Раз исходный код закрыт.

**Comment by GeekMagicClock** [comment]
> IMHO this software is based on an open source GPL licence - so we can just request the source code and they cannot refuse. https://github.com/peng-zhihui/HoloCubic/blob/main/LICENSE

NO, actually you don't know about it, otherwise you would not have made this wrong judgment about this model, they are different, again this is not open source for now, but possible in future.

**Comment by GeekMagicClock** [comment]
> Сделайте пожалуйста еще возможность запрашивать какие либо API что бы можно было засунуть туда что то свое, пробки или курс акций и т.д. Раз исходный код закрыт.

Sorry, no plans yet.

**Comment by GeekMagicClock** [comment]
> I just think this thing could be so much better if you got help from other developers via pull requests.

Appreciate your thoughts, but I don't want to complicate things at this moment, It's beyond my current ability.
