### ISSUE TITLE
Gif frozen when using auto switch themes

### ISSUE THREAD

**Issue by InfinityCyberpunk** [GeekMagicClock/HelloCubic-Lite#3]
It's just display animation of gif from photo album for a while before frozen when i use auto switch themes. I tried update firmware but still have that problem.

**Comment by GeekMagicClock** [comment]
@InfinityCyberpunk Hello, if the gif play time shorter than the auto switch interval, this will happen, that gif will be displayed once and then next gif, but if there's none, then frozen until time out, it's a known issue under development.
